front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

Front_vaccine:
    resource: "@FrontBundle/Controller/VaccineController.php"
    type:     annotation

Front_Event:
    resource: "@FrontBundle/Controller/EventController.php"
    type:     annotation

Front_Pediatrician:
    resource: "@FrontBundle/Controller/PediatricianController.php"
    type:     annotation

app_babysitter:
    resource: "@FrontBundle/Controller/BabySitterController.php"
    type:     annotation
web_service_vaccine:
    path:     /list_vaccine
    defaults: { _controller: FrontBundle:Vaccine:all }
